### PR TITLE
ksh 5 eslint added with required packages

### PR DESCRIPTION
**Pull request by oyiza**
this is a better and slightly simpler version of the eslint work. i have a better understanding now of what is done and the commit history is fine.

checkout this branch and try it out, you might initially see a lot of errors as this will clash with vscode eslint extension. if that happens follow these steps and hopefully it'll fix it:
- go to settings and uncheck `format on save` option if it's checked
    - also change `format on save mode` to `modifications`
- uninstall eslint extension
- restart vscode
- if the errors are gone, go ahead and install eslint extension again
- check the `format on save` option in vscode settings
- everything should be good

### CODE REVIEW

**Comment by oyiza** [comment]
@pandyama if this is good i'll close the other one.

**Comment by pandyama** [comment]
@oyiza i'll review it tonight after work. Yday i didnt get a chance & i was not feeling good, so I just took the evening off

**Comment by oyiza** [comment]
@pandyama all good man. no stress

**Comment by pandyama** [comment]
@oyiza i followed the steps and i didnt get any errors. The only thing i had to revert to was `format on save` to be `file`, when it was on ` modifications` the formatting was odd

**Review by pandyama — APPROVED** [review]

**Pull request merged**
